version: '3'
services:
  app:
    container_name: web-app
    volumes:
      - .:/app
    restart: always
    build: .
    ports:
      - '3000:3000'
    environment:
      - DB=""
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:4-focal
    restart: always 
    ports:
      - '27017:27017'