version: '3'
services:
  app:
    container_name: web-app
    volumes:
      - type: bind
          source: "/data/gv0/vols/aitor_node_web"
          target: "/app"
    restart: always
    image: aitor06/web-server-node
    ports:
      - '3000:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:4-focal
    restart: always 
    ports:
      - '27017:27017'
